kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: helloworld
  namespace: learnbyexample
spec:
  replicas: 2
  selector:
    matchLabels:
      k8s-app: helloworld
  template:
    metadata:
      name: helloworld
      labels:
        k8s-app: helloworld
    spec:
      containers:
        - name: helloworld
          image: docker.io/danielon30/helloworld:1.0