apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: learnbyexample
  name: quarkus-daemonset
  labels:
    app: quarkus-daemonset
spec:
  selector:
    matchLabels:
      app: quarkus-daemonset
  template:
    metadata:
      labels:
        app: quarkus-daemonset
    spec:
      containers:
      - name: quarkus-daemonset
        image: quay.io/danieloh30/todo-app:1.0